spring.datasource.url = jdbc:mysql://localhost:3306/student_db
spring.datasource.username = root
spring.datasource.password= your_database_password

spring.jpa.hibernate.ddl-auto=update //auto table creation and updation
spring.jpa.show-sql = true //lets us see the SQL queries in console

server.port = 8080